#############################################################################
# Makefile for building: HW4.app/Contents/MacOS/HW4
# Generated by qmake (3.1) (Qt 6.6.1)
# Project:  ../HW4/HW4.pro
# Template: app
# Command: /Users/vishal/qrt/6.6.1/macos/bin/qmake -o Makefile ../HW4/HW4.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wall -Wextra $(DEFINES)
INCPATH       = -I../HW4 -I. -I../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers -I../qrt/6.6.1/macos/lib/QtGui.framework/Headers -I../qrt/6.6.1/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I../qrt/6.6.1/macos/mkspecs/macx-clang -F/Users/vishal/qrt/6.6.1/macos/lib
QMAKE         = /Users/vishal/qrt/6.6.1/macos/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/vishal/qrt/6.6.1/macos/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/vishal/qrt/6.6.1/macos/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = HW41.0.0
DISTDIR = /Users/vishal/SocialNetwork/.tmp/HW41.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11.0 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/vishal/qrt/6.6.1/macos/lib
LIBS          = $(SUBLIBS) -F/Users/vishal/qrt/6.6.1/macos/lib -framework QtWidgets -framework QtGui -framework AppKit -framework ImageIO -framework Metal -framework QtCore -framework IOKit -framework DiskArbitration -framework AGL -framework OpenGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = network.cpp \
		post.cpp \
		user.cpp \
		../HW4/main.cpp \
		../HW4/mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = network.o \
		post.o \
		user.o \
		main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = ../qrt/6.6.1/macos/mkspecs/features/spec_pre.prf \
		../qrt/6.6.1/macos/mkspecs/features/device_config.prf \
		../qrt/6.6.1/macos/mkspecs/common/unix.conf \
		../qrt/6.6.1/macos/mkspecs/common/mac.conf \
		../qrt/6.6.1/macos/mkspecs/common/macx.conf \
		../qrt/6.6.1/macos/mkspecs/common/sanitize.conf \
		../qrt/6.6.1/macos/mkspecs/common/gcc-base.conf \
		../qrt/6.6.1/macos/mkspecs/common/gcc-base-mac.conf \
		../qrt/6.6.1/macos/mkspecs/common/clang.conf \
		../qrt/6.6.1/macos/mkspecs/common/clang-mac.conf \
		../qrt/6.6.1/macos/mkspecs/qconfig.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_core.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_help.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_network.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../qrt/6.6.1/macos/mkspecs/features/qt_functions.prf \
		../qrt/6.6.1/macos/mkspecs/features/qt_config.prf \
		../qrt/6.6.1/macos/mkspecs/macx-clang/qmake.conf \
		../qrt/6.6.1/macos/mkspecs/features/spec_post.prf \
		../qrt/6.6.1/macos/mkspecs/features/exclusive_builds.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/sdk.prf \
		../qrt/6.6.1/macos/mkspecs/features/toolchain.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/toolchain.prf \
		../qrt/6.6.1/macos/mkspecs/features/default_pre.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/default_pre.prf \
		../qrt/6.6.1/macos/mkspecs/features/resolve_config.prf \
		../qrt/6.6.1/macos/mkspecs/features/default_post.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/default_post.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/objective_c.prf \
		../qrt/6.6.1/macos/mkspecs/features/qml_debug.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/mac.prf \
		../qrt/6.6.1/macos/mkspecs/features/warn_on.prf \
		../qrt/6.6.1/macos/mkspecs/features/permissions.prf \
		../qrt/6.6.1/macos/mkspecs/features/qt.prf \
		../qrt/6.6.1/macos/mkspecs/features/resources_functions.prf \
		../qrt/6.6.1/macos/mkspecs/features/resources.prf \
		../qrt/6.6.1/macos/mkspecs/features/moc.prf \
		../qrt/6.6.1/macos/mkspecs/features/unix/opengl.prf \
		../qrt/6.6.1/macos/mkspecs/features/uic.prf \
		../qrt/6.6.1/macos/mkspecs/features/unix/thread.prf \
		../qrt/6.6.1/macos/mkspecs/features/qmake_use.prf \
		../qrt/6.6.1/macos/mkspecs/features/file_copies.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/rez.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../qrt/6.6.1/macos/mkspecs/features/testcase_targets.prf \
		../qrt/6.6.1/macos/mkspecs/features/exceptions.prf \
		../qrt/6.6.1/macos/mkspecs/features/yacc.prf \
		../qrt/6.6.1/macos/mkspecs/features/lex.prf \
		../HW4/HW4.pro network.h \
		post.h \
		user.h \
		../HW4/mainwindow.h network.cpp \
		post.cpp \
		user.cpp \
		../HW4/main.cpp \
		../HW4/mainwindow.cpp
QMAKE_TARGET  = HW4
DESTDIR       = 
TARGET        = HW4.app/Contents/MacOS/HW4

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 14.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = 
EXPORT_VALID_ARCHS = x86_64 arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/vishal/HW4/HW4.pro


include /Users/vishal/qrt/6.6.1/macos/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

HW4.app/Contents/MacOS/HW4: ui_mainwindow.h $(OBJECTS)  
	@test -d HW4.app/Contents/MacOS/ || mkdir -p HW4.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../HW4/HW4.pro ../qrt/6.6.1/macos/mkspecs/macx-clang/qmake.conf ../qrt/6.6.1/macos/mkspecs/features/spec_pre.prf \
		../qrt/6.6.1/macos/mkspecs/features/device_config.prf \
		../qrt/6.6.1/macos/mkspecs/common/unix.conf \
		../qrt/6.6.1/macos/mkspecs/common/mac.conf \
		../qrt/6.6.1/macos/mkspecs/common/macx.conf \
		../qrt/6.6.1/macos/mkspecs/common/sanitize.conf \
		../qrt/6.6.1/macos/mkspecs/common/gcc-base.conf \
		../qrt/6.6.1/macos/mkspecs/common/gcc-base-mac.conf \
		../qrt/6.6.1/macos/mkspecs/common/clang.conf \
		../qrt/6.6.1/macos/mkspecs/common/clang-mac.conf \
		../qrt/6.6.1/macos/mkspecs/qconfig.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_ext_freetype.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_ext_libjpeg.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_ext_libpng.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_concurrent.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_core.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_core_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_dbus.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_dbus_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designer.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designer_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_freetype_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_gui.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_gui_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_help.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_help_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsanimation.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssettings.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_linguist.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_linguist_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_network.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_network_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_opengl.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_opengl_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_png_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_printsupport.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qml.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qml_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcore.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltest.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quick.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quick_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_sql.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_sql_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svg.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svg_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_testlib.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_testlib_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_tools_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uiplugin.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uitools.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uitools_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_widgets.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_widgets_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_xml.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_lib_xml_private.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri \
		../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri \
		../qrt/6.6.1/macos/mkspecs/features/qt_functions.prf \
		../qrt/6.6.1/macos/mkspecs/features/qt_config.prf \
		../qrt/6.6.1/macos/mkspecs/macx-clang/qmake.conf \
		../qrt/6.6.1/macos/mkspecs/features/spec_post.prf \
		../qrt/6.6.1/macos/mkspecs/features/exclusive_builds.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/sdk.prf \
		../qrt/6.6.1/macos/mkspecs/features/toolchain.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/toolchain.prf \
		../qrt/6.6.1/macos/mkspecs/features/default_pre.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/default_pre.prf \
		../qrt/6.6.1/macos/mkspecs/features/resolve_config.prf \
		../qrt/6.6.1/macos/mkspecs/features/default_post.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/default_post.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/objective_c.prf \
		../qrt/6.6.1/macos/mkspecs/features/qml_debug.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/mac.prf \
		../qrt/6.6.1/macos/mkspecs/features/warn_on.prf \
		../qrt/6.6.1/macos/mkspecs/features/permissions.prf \
		../qrt/6.6.1/macos/mkspecs/features/qt.prf \
		../qrt/6.6.1/macos/mkspecs/features/resources_functions.prf \
		../qrt/6.6.1/macos/mkspecs/features/resources.prf \
		../qrt/6.6.1/macos/mkspecs/features/moc.prf \
		../qrt/6.6.1/macos/mkspecs/features/unix/opengl.prf \
		../qrt/6.6.1/macos/mkspecs/features/uic.prf \
		../qrt/6.6.1/macos/mkspecs/features/unix/thread.prf \
		../qrt/6.6.1/macos/mkspecs/features/qmake_use.prf \
		../qrt/6.6.1/macos/mkspecs/features/file_copies.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/rez.prf \
		../qrt/6.6.1/macos/mkspecs/features/mac/asset_catalogs.prf \
		../qrt/6.6.1/macos/mkspecs/features/testcase_targets.prf \
		../qrt/6.6.1/macos/mkspecs/features/exceptions.prf \
		../qrt/6.6.1/macos/mkspecs/features/yacc.prf \
		../qrt/6.6.1/macos/mkspecs/features/lex.prf \
		../HW4/HW4.pro \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		../qrt/6.6.1/macos/lib/QtGui.framework/Resources/QtGui.prl \
		../qrt/6.6.1/macos/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile ../HW4/HW4.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug
../qrt/6.6.1/macos/mkspecs/features/spec_pre.prf:
../qrt/6.6.1/macos/mkspecs/features/device_config.prf:
../qrt/6.6.1/macos/mkspecs/common/unix.conf:
../qrt/6.6.1/macos/mkspecs/common/mac.conf:
../qrt/6.6.1/macos/mkspecs/common/macx.conf:
../qrt/6.6.1/macos/mkspecs/common/sanitize.conf:
../qrt/6.6.1/macos/mkspecs/common/gcc-base.conf:
../qrt/6.6.1/macos/mkspecs/common/gcc-base-mac.conf:
../qrt/6.6.1/macos/mkspecs/common/clang.conf:
../qrt/6.6.1/macos/mkspecs/common/clang-mac.conf:
../qrt/6.6.1/macos/mkspecs/qconfig.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_ext_freetype.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_ext_libjpeg.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_ext_libpng.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_concurrent.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_concurrent_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_core.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_core_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_dbus.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_dbus_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designer.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designer_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_designercomponents_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_example_icons_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_fb_support_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_freetype_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_gui.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_gui_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_help.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_help_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_jpeg_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsanimation.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsanimation_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssettings.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssettings_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssharedimage.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_linguist.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_linguist_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_network.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_network_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_opengl.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_opengl_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_openglwidgets.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_png_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_printsupport.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_printsupport_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatch_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qml.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qml_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcompiler.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcore.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlcore_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmldebug_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmldom_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlintegration.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlls_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlmodels.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltest.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltest_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quick.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quick_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickeffects_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicklayouts.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickparticles_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickshapes_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktemplates2.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickwidgets.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_sql.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_sql_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svg.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svg_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svgwidgets.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_testlib.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_testlib_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_tools_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uiplugin.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uitools.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_uitools_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_widgets.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_widgets_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_xml.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_lib_xml_private.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinbluetoothpermission.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincalendarpermission.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincamerapermission.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwincontactspermission.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinlocationpermission.pri:
../qrt/6.6.1/macos/mkspecs/modules/qt_plugin_qdarwinmicrophonepermission.pri:
../qrt/6.6.1/macos/mkspecs/features/qt_functions.prf:
../qrt/6.6.1/macos/mkspecs/features/qt_config.prf:
../qrt/6.6.1/macos/mkspecs/macx-clang/qmake.conf:
../qrt/6.6.1/macos/mkspecs/features/spec_post.prf:
../qrt/6.6.1/macos/mkspecs/features/exclusive_builds.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/sdk.prf:
../qrt/6.6.1/macos/mkspecs/features/toolchain.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/toolchain.prf:
../qrt/6.6.1/macos/mkspecs/features/default_pre.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/default_pre.prf:
../qrt/6.6.1/macos/mkspecs/features/resolve_config.prf:
../qrt/6.6.1/macos/mkspecs/features/default_post.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/default_post.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/objective_c.prf:
../qrt/6.6.1/macos/mkspecs/features/qml_debug.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/mac.prf:
../qrt/6.6.1/macos/mkspecs/features/warn_on.prf:
../qrt/6.6.1/macos/mkspecs/features/permissions.prf:
../qrt/6.6.1/macos/mkspecs/features/qt.prf:
../qrt/6.6.1/macos/mkspecs/features/resources_functions.prf:
../qrt/6.6.1/macos/mkspecs/features/resources.prf:
../qrt/6.6.1/macos/mkspecs/features/moc.prf:
../qrt/6.6.1/macos/mkspecs/features/unix/opengl.prf:
../qrt/6.6.1/macos/mkspecs/features/uic.prf:
../qrt/6.6.1/macos/mkspecs/features/unix/thread.prf:
../qrt/6.6.1/macos/mkspecs/features/qmake_use.prf:
../qrt/6.6.1/macos/mkspecs/features/file_copies.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/rez.prf:
../qrt/6.6.1/macos/mkspecs/features/mac/asset_catalogs.prf:
../qrt/6.6.1/macos/mkspecs/features/testcase_targets.prf:
../qrt/6.6.1/macos/mkspecs/features/exceptions.prf:
../qrt/6.6.1/macos/mkspecs/features/yacc.prf:
../qrt/6.6.1/macos/mkspecs/features/lex.prf:
../HW4/HW4.pro:
../qrt/6.6.1/macos/lib/QtWidgets.framework/Resources/QtWidgets.prl:
../qrt/6.6.1/macos/lib/QtGui.framework/Resources/QtGui.prl:
../qrt/6.6.1/macos/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../HW4/HW4.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE

HW4.app/Contents/PkgInfo: 
	@test -d HW4.app/Contents || mkdir -p HW4.app/Contents
	@$(DEL_FILE) HW4.app/Contents/PkgInfo
	@echo "APPL????" > HW4.app/Contents/PkgInfo
HW4.app/Contents/Info.plist: 
	@test -d HW4.app/Contents || mkdir -p HW4.app/Contents
	@$(DEL_FILE) HW4.app/Contents/Info.plist
	@plutil -convert xml1 -o - ../qrt/6.6.1/macos/mkspecs/macx-clang/Info.plist.app | sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.HW4,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.HW4,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},11.0,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,\$${IOS_LAUNCH_SCREEN},LaunchScreen,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,HW4,g" -e "s,@LIBRARY@,HW4,g" -e "s,\$${EXECUTABLE_NAME},HW4,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" >HW4.app/Contents/Info.plist

all: Makefile \
		HW4.app/Contents/PkgInfo \
		HW4.app/Contents/Info.plist HW4.app/Contents/MacOS/HW4

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents network.h post.h user.h ../HW4/mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents network.cpp post.cpp user.cpp ../HW4/main.cpp ../HW4/mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../HW4/mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r HW4.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../HW4/mainwindow.h \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		user.h \
		post.h \
		../qrt/6.6.1/macos/libexec/moc
	/Users/vishal/qrt/6.6.1/macos/libexec/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -D__cplusplus=199711L -D__APPLE_CC__=6000 -D__clang__ -D__clang_major__=15 -D__clang_minor__=0 -D__clang_patchlevel__=0 -D__GNUC__=4 -D__GNUC_MINOR__=2 -D__GNUC_PATCHLEVEL__=1 -I/Users/vishal/qrt/6.6.1/macos/mkspecs/macx-clang -I/Users/vishal/HW4 -I/Users/vishal/qrt/6.6.1/macos/lib/QtWidgets.framework/Headers -I/Users/vishal/qrt/6.6.1/macos/lib/QtGui.framework/Headers -I/Users/vishal/qrt/6.6.1/macos/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/Users/vishal/qrt/6.6.1/macos/lib ../HW4/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../HW4/mainwindow.ui \
		../qrt/6.6.1/macos/libexec/uic
	/Users/vishal/qrt/6.6.1/macos/libexec/uic ../HW4/mainwindow.ui -o ui_mainwindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

network.o: network.cpp network.h \
		user.h \
		post.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

post.o: post.cpp post.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o post.o post.cpp

user.o: user.cpp user.h \
		post.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o user.o user.cpp

main.o: ../HW4/main.cpp ../HW4/mainwindow.h \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		user.h \
		post.h \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/QApplication \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../HW4/main.cpp

mainwindow.o: ../HW4/mainwindow.cpp ../HW4/mainwindow.h \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/QMainWindow \
		../qrt/6.6.1/macos/lib/QtWidgets.framework/Headers/qmainwindow.h \
		user.h \
		post.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../HW4/mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/HW4/bin || mkdir -p $(INSTALL_ROOT)/opt/HW4/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/HW4/bin/HW4.app
	
	$(QINSTALL) HW4.app $(INSTALL_ROOT)/opt/HW4/bin/HW4.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/HW4/bin/HW4.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/HW4/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

